drifters/urls.py
from django.urls import path

from . import views

app_name = "drifters"

urlpatterns = [
    path("", views.index, name="index"),
    path("motd", views.motd, name="motd"),
    path("scout", views.scout, name="scout"),
    path("scout/region/<int:region_id>/", views.scout_region, name="scout_region"),
    path("scout/complex/<str:complex>/", views.scout_complex, name="scout_complex"),
]

drifters/templates/drifters/scout/blocks/scout_complex.html
{% load i18n %}
{% load drifters %}
<div class="col-lg-4">
    {% if count == update_older_than_12h %}
        <div class="panel panel-danger">
        {% elif count == update_older_than_8h %}
            <div class="panel panel-warning">
            {% elif count == update_older_than_4h %}
                <div class="panel panel-info">
                {% else %}
                    <div class="panel panel-success">
                    {% endif %}

                    <div class="panel-heading">
                        <div class="panel-title">{{ complex }} x {{ count }}</div>
                    </div>
                    <div class="panel-body">
                        update_older_than_4h: {{ update_older_than_4h }}
                        <br />
                        update_older_than_8h: {{ update_older_than_8h }}
                        <br />
                        update_older_than_12h: {{ update_older_than_12h }}
                        <br />
                    </div>
                    <div class="panel-footer">
                        <a name="Scout" class="btn btn-primary" href={% url "drifters:scout_complex" complex=complex %} role="button">Scout</a>
                    </div>
                </div>
            </div>

drifters/templates/drifters/scout/blocks/scout_region.html
{% load i18n %}
{% load drifters %}
<div class="col-lg-4">
    {% if count == update_older_than_12h %}
        <div class="panel panel-danger">
        {% elif count == update_older_than_8h %}
            <div class="panel panel-warning">
            {% elif count == update_older_than_4h %}
                <div class="panel panel-info">
                {% else %}
                    <div class="panel panel-success">
                    {% endif %}

                    <div class="panel-heading">
                        <div class="panel-title">{{ region }} x {{ count }}</div>
                    </div>
                    <div class="panel-body">
                        update_older_than_4h: {{ update_older_than_4h }}
                        <br />
                        update_older_than_8h: {{ update_older_than_8h }}
                        <br />
                        update_older_than_12h: {{ update_older_than_12h }}
                        <br />
                    </div>
                    <div class="panel-footer">
                        <a name="Scout" class="btn btn-primary" href={% url "drifters:scout_region" region_id=region.id %} role="button">Scout</a>
                    </div>
                </div>
            </div>

drifters/templates/drifters/scout/blocks/scout_system.html
{% load bootstrap %}
{{ system }}
<br />
<form method="post">
    {% csrf_token %}
    {{ formset.management_form }}
    <table>
        {{ formset }}
    </table>
    <button>Add</button>
</form>
<br />