drifters/urls.py
from django.urls import path

from . import views

app_name = "drifters"

urlpatterns = [
    path("", views.index, name="index"),
    path("motd", views.motd, name="motd"),
    path("scout", views.scout, name="scout"),
    path("scout/region/<int:region_id>/", views.scout_region, name="scout_region"),
    path("scout/complex/<str:complex>/", views.scout_complex, name="scout_complex"),
]

drifters/templates/drifters/base.html
{% extends "allianceauth/base.html" %}
{% load i18n %}
{% load humanize %}
{% load static %}
{% block page_title %}
    {% translate "Drifters" %}
{% endblock page_title %}
{% block content %}
    <div class="container-fluid aa-drifters">
        <br />
        <nav class="navbar navbar-default">
            <div class="navbar-header">
                <button type="button"
                        class="navbar-toggle collapsed"
                        data-toggle="collapse"
                        data-target="#drifters-navbar-collapse-1"
                        aria-expanded="false">
                    <span class="sr-only">{% translate "Toggle navigation" %}</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'drifters:index' %}">{% translate "Drifters" %}</a>
            </div>
            <div class="collapse navbar-collapse" id="drifters-navbar-collapse-1">
                <ul class="nav navbar-nav pull-right">
                    <li>
                        <a href="{% url 'drifters:motd' %}">{% translate "MOTD Generator" %}</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li>
                        <a href="{% url 'drifters:scout' %}">{% translate "Scout Interface" %}</a>
                    </li>
                </ul>
            </div>
        </nav>
        {% block details %}
        {% endblock details %}
    </div>
{% endblock content %}

drifters/templates/drifters/index.html
{% extends "drifters/base.html" %}
{% load i18n %}
{% load humanize %}
{% block details %}
    <div class="row">
        {% for complex in complex_renders %}{{ complex }}{% endfor %}
    </div>
{% endblock details %}

drifters/templates/drifters/motd.html
{% extends "drifters/base.html" %}
{% load i18n %}
{% load humanize %}
{% block details %}
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title">MOTD Generator</div>
                </div>
                <div class="panel-body">
                    <pre id="motd_textblock">{{ motd_1 }}</pre>
                    <pre id="motd_textblock">{{ motd_2 }}</pre>
                    <button class="btn btn-success" id="CopyMOTDButtonHeader" data-clipboard-text="{{ motd_1 }}">
                        {% translate "Copy MOTD Headers" %}
                    </button>
                    <button class="btn btn-success" id="CopyMOTDButtonRoutes" data-clipboard-text="{{ motd_2 }}">
                        {% translate "Copy MOTD Routes" %}
                    </button>
                </div>
            </div>
        </div>
    </div>
{% endblock details %}

{% block extra_javascript %}
    {% include "bundles/clipboard-js.html" %}
    <script>
        new ClipboardJS('#CopyMOTDButtonHeader');
        new ClipboardJS('#CopyMOTDButtonRoutes');
    </script>
{% endblock extra_javascript %}